#!/bin/bash

RESTRICTED_PATHS="/rbin|/bin|/usr|/sbin|/lib|/etc|/libexec|/boot|/sys|/proc|/dev|/var|/opt|/local"
ALLOWED_SUBPATHS="/var/run|/var/tmp|/var/log"
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
export PATH

exe=`basename $0`
last_arg_fail=0
for arg in "$@"
do
	last_arg_fail=0
	echo $arg | grep -E $RESTRICTED_PATHS > /dev/null
	if [ $? -eq 0 ]
	then
		echo $arg | grep -E $ALLOWED_SUBPATHS > /dev/null
		if [ $? -ne 0 ]
		then
			if [ "$exe" != "scp" ]
			then
				echo "You are not allowed to mess around within a restricted shell."
				echo
				exit 1
			else
				last_arg_failed=1
			fi
		fi
	fi
done

if [ "$exe" = "scp" -a $last_arg_fail -eq 1 ]
then
	echo "You are not allowed to mess around within a restricted shell."
	echo
	exit 1
fi

if [ "$exe" = "vi" ]
then
	exec ${exe} -Z "$@"
else
	exec ${exe} "$@"
fi

